### ISSUE TITLE
Support for Django 1.11

### ISSUE THREAD

**Issue by nichcz** [denisenkom/django-sqlserver#13]
I'm using this backend on Django 1.10 without any problems. And as [Django 1.11 is now out](https://www.djangoproject.com/weblog/2017/apr/04/django-111-released/), is there any chance for support?

Tried on Django 1.11 and is seems that client_class is not implemented.
```
Traceback (most recent call last):
  ...

  File "/project/virtual/local/lib/python2.7/site-packages/django/db/models/query.py", line 50, in __iter__
    compiler = queryset.query.get_compiler(using=db)
  File "/project/virtual/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 255, in get_compiler
    connection = connections[using]
  File "/project/virtual/local/lib/python2.7/site-packages/django/db/utils.py", line 212, in __getitem__
    conn = backend.DatabaseWrapper(db, alias)
  File "/project/virtual/local/lib/python2.7/site-packages/sqlserver/base.py", line 80, in __init__
    super(DatabaseWrapper, self).__init__(*args, **kwargs)
  File "/project/virtual/local/lib/python2.7/site-packages/sqlserver_ado/base.py", line 184, in __init__
    super(DatabaseWrapper, self).__init__(*args, **kwargs)
  File "/project/virtual/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 96, in __init__
    self.client = self.client_class(self)
TypeError: 'NoneType' object is not callable
```

**Comment by nichcz** [comment]
I have just created pull request for this https://github.com/denisenkom/django-sqlserver/pull/14.

**Comment by danchr** [comment]
Thank you — and I see @denisenkom merged pull request. Could we perhaps get a release with this?

**Comment by frague59** [comment]
+1

**Comment by denisenkom** [comment]
uploaded new version to pypi https://pypi.python.org/pypi/django-sqlserver/1.11
